spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080